- src/main/java/org/mule/runtime/api/message/Message.java
_ InternalMessage and some related classes will be part of the privileged API.
To make that change, org.mule.runtime.api.message.AbstractMuleMessageBuilderFactory will have to use the container classloader to find the message factory, instead of using the current thread's context classloader.
By doing that change, extensions maven plugin will fail to process extensions that have Message on their API.
The problem is that the plugin depends on mule-api only, which is correct. But Message has a Message constant that has to be built. As the plugin has no dependency on mule-core, there is no message implementation that can be found.
The fix at this moment is just to inline this constant, we will have to review if the approach used to separated mule API from the implementation is the right one.
> MULE-11654: Define privileged API

- src/main/java/org/mule/runtime/api/exception/DefaultExceptionReader.java
- src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java
- src/main/java/org/mule/runtime/api/exception/MuleException.java
- src/main/java/org/mule/runtime/api/exception/MuleExceptionReader.java
- src/main/java/org/mule/runtime/api/exception/MuleRuntimeException.java
- src/main/java/org/mule/runtime/api/exception/NamingExceptionReader.java
- src/main/java/org/mule/runtime/api/legacy/exception/ExceptionReader.java
disabled
* Add generics to exception info
* Migrate uses of deprecated `SystemUtils.LINE_SEPARATOR`
> MULE-12832: Avoid generating stacktraces for exceptions when verbose is

- src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java
_ Moving org.mule.runtime.core.processor to internal/api (WIP)
> MULE-13007: Every exported Mule package must contain api (part3)

- src/main/java/org/mule/runtime/api/event/Event.java
> MULE-13211: Correlation information is not exposed in the interception

- pom.xml
- src/main/java/org/mule/runtime/api/connectivity/ConnectivityTestingStrategy.java
- src/main/java/org/mule/runtime/api/connectivity/UnsupportedConnectivityTestingObjectException.java
- src/main/java/org/mule/runtime/api/exception/DefaultMuleException.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerBusyException.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerConfig.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerContainerPoolsConfig.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerPoolsConfig.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerPoolsConfigFactory.java
- src/main/java/org/mule/runtime/api/scheduler/SchedulerService.java
- src/main/java/org/mule/runtime/api/store/ObjectStoreToMapAdapter.java
- src/main/java/org/mule/runtime/api/store/SimpleMemoryObjectStore.java
- src/main/java/org/mule/runtime/api/time/TimeSupplier.java
- src/main/java/org/mule/runtime/api/util/collection/Collectors.java
- src/main/java/org/mule/runtime/internal/util/collection/ImmutableEntry.java
- src/main/java/org/mule/runtime/internal/util/collection/ImmutableListCollector.java
- src/main/java/org/mule/runtime/internal/util/collection/ImmutableMapCollector.java
- src/main/java/org/mule/runtime/internal/util/collection/ImmutableSetCollector.java
- src/main/resources/META-INF/mule-module.properties
_ Moving classes out of core's api package
_ When possible, classes where moved to internal
_ Moved to privileged when classes where required on compatibility
_ Moved to other module's API when needed on tests or it made sense
_ Deleted if not needed anymore
_ Some tests were ignored as they use an internal class and need refactoring
> MULE-13545: Cleanup core API

- src/main/java/org/mule/runtime/api/service/ServiceRepository.java
_ Enabling injection of ServiceRepository and service instances on core extensions by defining fields or setters annotated with @Inject
> MULE-13210: Allow Core Extensions to Inject container services

- src/main/java/org/mule/runtime/api/exception/MuleException.java
- Refactor on `org.mule.runtime.api.exception.MuleException#getSummaryMessage` method
- This issue is the root cause of the `mule-aggregators-module`tests failing on Windows
> MULE-15932: System dependent line separators should be used for building Mule exception summary message

- src/main/java/org/mule/runtime/api/component/DefaultTypedComponentIdentifier.java
- src/main/java/org/mule/runtime/api/meta/model/stereotype/HasStereotypeModel.java
- src/main/java/org/mule/runtime/api/meta/model/stereotype/StereotypeModel.java
* Also piggyback some improvements in some javadocs
> MULE-17672: Make DefaultTypedComponentIdentifier#hashCode consistent across runs

- src/main/java/org/mule/runtime/api/el/ExpressionLanguageSession.java
> MULE-17782: Add support for compile method on ExpressionLanguage

- src/main/java/org/mule/runtime/api/deployment/management/ComponentInitialStateManager.java
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
It revers changes introduced in PR #637 because this feature already exists.  Also, it deprecates the System Property DISABLE_SCHEDULER_SOURCES_PROPERTY and adds this property in the MuleSystemProperties class.
> MULE-18063: Revert changes

- src/main/java/org/mule/runtime/api/scheduler/SchedulingStrategy.java
> MULE-18422: `Scheduler` infrastructure type not visible outside of

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 5b8883a29fa5939e8cec4fc1d03a97fb54661f03)
(cherry picked from commit 3401a17a294e21e3103d69c2f5633a518262390e)
> MULE-18196: Application fails to deploy when having same custom name space as that of custom policy applied

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 5b8883a29fa5939e8cec4fc1d03a97fb54661f03)
> MULE-18196: Application fails to deploy when having same custom name space as that of custom policy applied (branch support/1.2.2)

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 5b8883a29fa5939e8cec4fc1d03a97fb54661f03)
> MULE-18196: Application fails to deploy when having same custom name space as that of custom policy applied (branch support/1.3.x)

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 5b8883a29fa5939e8cec4fc1d03a97fb54661f03)
> MULE-18196: Application fails to deploy when having same custom name space as that of custom policy applied (branch support/1.2.x)

- api-changes.json
- src/main/java/org/mule/runtime/api/streaming/CursorProvider.java
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 784a970a5a542ec6bb7dd77cdd4e3c2dc5daef44)
(cherry picked from commit c00415caf37b2151dbdb615f00a679182391fe8b)
> MULE-18047: Add the component that generated a cursor provider (support/1.2.2)

- api-changes.json
- src/main/java/org/mule/runtime/api/streaming/CursorProvider.java
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
… (#674)
(cherry picked from commit 784a970a5a542ec6bb7dd77cdd4e3c2dc5daef44)
(cherry picked from commit c00415caf37b2151dbdb615f00a679182391fe8b)
> MULE-18047: Add the component that generated a cursor provider (support/1.2.1)

- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit ee5c535ac84b528645e03299001e5bdafdc46c0d)
> MULE-18573: CursorProvider key collision at CursorProvider cache (#703)

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
sub-flow's in 4.2.x and lower (#751)
> MULE-19110: munit:enable-flow-sources could be used to initialize

- src/main/java/org/mule/runtime/api/metadata/MediaType.java
- src/test/java/org/mule/runtime/api/metadata/MediaTypeTestCase.java
* MULE-19219: MediaType doesn't escape characters correctly
* Tests that shows the bug
Co-authored-by: machaval <mariano.achaval@mulesoft.com>
(cherry picked from commit 6573cb774a1440fdf4a91153c6bda4401b93f15d)
> MULE-19219: MediaType doesn't escape characters correctly (#787)

- src/main/java/org/mule/runtime/api/el/MuleExpressionLanguage.java
> MULE-19468: LazyExpressionManager not setting correct TCCL when calling DW

- src/main/java/org/mule/runtime/api/store/ObjectStoreSettings.java
> Revert "MULE-19992: Private object stores should be able to be expired in secondary node", further analysis required

- src/main/java/org/mule/runtime/api/util/CaseInsensitiveMapWrapper.java
- src/main/java/org/mule/runtime/api/util/MultiMap.java
* Optimizing keyFor by avoiding unnecessary calls for size computation on the ConcurrentHashMap.
* A few optimizations on MultiMap to avoid unnecessary hash computations.
(cherry picked from commit d2989f4d0a335d322c39a8427adbeb6895938440)
> EE-8118: Optimizations for the HTTP proxy path

- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
This is related to changes needed in https://github.com/mulesoft/mule-ee/pull/4334
(Change BouncyCastleFipsProvider to use hybrid entropy config option to avoid Mule runtime hanging at startup in some linux version)
> W-11178986: Add property MULE_SECURITY_PROVIDER_ENABLE_HYBRID_DRBG

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit be225153936c12964a2ca1d18014d0c6e7faf0e4)
> W-12181063: [Global Error Handling] remove the kill switch for enabling the memory fixes in 4.5 (#1089)

- api-changes.json
- src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
(cherry picked from commit 3d3ff201405247899206dbe9eb1b2efa3be45c7d)
> W-12218381: [Global Error Handling] remove the system property reuse.globalErrorHandler in 4.3/4.4 and replace with a kill switch (#1091)

- api-changes.json
- pom.xml
> W-13517980: Revapi validation must point to latest stable version, not a

- src/main/java/org/mule/runtime/api/metadata/MediaType.java
- src/test/java/org/mule/runtime/api/test/metadata/MediaTypeTestCase.java
The cache usage was removed accidentally in 3427625. This caused a degradation in some of our benchmarks. We're restoring the cache usage.
Apart of that, to avoid re-calculating the constant MetadataType values, we're removing them from the cache and introducing a new map of predefined types.
We have tested 4.6.0-rc2 vs 4.6.0-rc3 vs a custom runtime with 4.6.0-rc3 plus this change. Here is a graphic showing the degradation and the improvement:
> W-14678431: Use the MetadataType cache again, and separate the constant types in a separate map

- src/main/java/org/mule/runtime/api/metadata/MediaType.java
- src/test/java/org/mule/runtime/api/test/metadata/MediaTypeTestCase.java
(cherry picked from commit ddf5538d77faba4c7f1b6ebc3f7f44ec592b3f4c)
> W-14678431: Use the MetadataType cache again, and separate the constant types in a separate map (#1286)

- src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
- src/test/java/module-info.java
- src/test/java/org/mule/runtime/api/test/component/DefaultComponentIdentifierTestCase.java
**Problem**: The Mule app fails to deploy due to an error in the raise-error component when the error type is provided with an extra space at the end (e.g., type="ERROR:404 BAD DATA "). The regression was caught in this [bug](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001wkZveYAE/view).
**What was the error?**
Customers can specify the error type string in the XML. In this case, the user provided the error type as “ERROR:404 BAD DATA ” in the component. When the Mule application parsed the XML file and tried to build the AST tree, it encountered an error as it was trying to get the error type for “ERROR:404 BAD DATA” in the errorTypeRepository. This caused the application to fail to deploy for Mule version 4.5+.
On further investigation we also reproduced the following …
> W-16237424 Add trim to() DefaultComponentIdentifier builder

- src/main/java/module-info.java
This one is needed only in 4.6 because in newer branches we already have this one: https://github.com/mulesoft/mule-api/commit/d7e6c15e4a77a63e2a703f934b60e7689917f08b
> W-17774685: Fix serialization of Result objects with Java 17
