mulesoft/mule-api

src/main/java/org/mule/runtime/api/service/Service.java

MULE-10160 - Move lifecycle interfaces to mule-api

---

src/main/java/org/mule/runtime/api/util/CaseInsensitiveMapWrapper.java
src/test/java/org/mule/runtime/api/util/CaseInsensitiveMapWrapperTestCase.java

- Move case insensitive map solution to api

MULE-10760: HTTP Service - Create request and response builders

---

src/main/resources/META-INF/mule-module.properties

MULE-11287: Copy bulk operation classes from mule-commons to mule-api

---

src/main/java/org/mule/runtime/api/metadata/TypedValue.java

DefaultTypedValue from mule-core

MULE-11364: Replace TypedValue interface on mule-api with

---

src/main/java/org/mule/runtime/api/component/ComponentIdentifier.java
src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
src/main/java/org/mule/runtime/api/meta/model/XmlDslModel.java

MULE-11856: @Xml annotation attributes renaming, fix broken build

Mule 11856 fix

---

pom.xml

depends on https://github.com/mulesoft/metadata-model-api/pull/62

MULE-11289: renaming groupsIds

---

src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java
src/main/java/org/mule/runtime/api/i18n/I18nMessageFactory.java

_ Moving resources files out of META-INF/services folder

MULE-12007: Container must not export every service through SPI

---

src/main/java/org/mule/runtime/api/message/Message.java

MULE-12086: Clean up Message API to avoid exposing InternalMessage

---

src/main/java/org/mule/runtime/api/message/Message.java

Requires merging at the same time in mule, mule-ee, mule-api, mule-compatibility-plugin and mule-extensions-api

MULE-10774: make attributes a TypedValue

---

src/main/java/org/mule/runtime/api/message/AbstractMuleMessageBuilderFactory.java

_ Using the container classloader to search using SPI

MULE-11654: Define privileged API

---

pom.xml

MULE-12345: Maven dependency resolution doesn't output logs

---

src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/AbstractOperationDeclarer.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ComponentDeclaration.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/OperationDeclaration.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/SourceDeclaration.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/SourceDeclarer.java
src/main/java/org/mule/runtime/api/meta/model/source/SourceModel.java

MULE-12448: Sources error handling is inconsistent

---

src/main/java/org/mule/runtime/api/deployment/meta/MuleApplicationModel.java
src/main/java/org/mule/runtime/api/deployment/meta/MuleDeployableModel.java
src/main/java/org/mule/runtime/api/deployment/meta/MuleDomainModel.java
src/main/java/org/mule/runtime/api/deployment/persistence/MuleDomainModelJsonSerializer.java

_ Adding domain model
_ Refactoring

MULE-9653: Add a way to share application plugins on the domain

---

src/main/java/org/mule/runtime/api/metadata/MetadataKeyBuilder.java

(cherry picked from commit cf23ab2)

MULE-12889: Metadata is not resolved for SOAP-based connectors

---

src/main/java/org/mule/runtime/api/interception/InterceptionEvent.java

MULE-11876: Provide a standard way to build a BindingContext from an

---

src/main/java/org/mule/runtime/api/store/ObjectStoreManager.java

_ Adding missing changes from original commits

MULE-12903: Every exported Mule package must contain api (part2)

---

src/main/java/org/mule/runtime/api/meta/model/ExtensionModel.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ExtensionDeclaration.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ExtensionDeclarer.java

_ Updating API to support exporting privileged packages on extensions

MULE-13011: Add privileged API for plugin artifacts

---

src/main/java/org/mule/runtime/api/el/BindingContextUtils.java

MULE-13062: Make bindings in Scripting module consistent with EL

---

src/main/java/org/mule/runtime/api/meta/AnnotatedObject.java
src/main/java/org/mule/runtime/api/util/ComponentLocationProvider.java

MULE-11065: Make all configuration components AnnotatedObject

---

src/main/java/org/mule/runtime/api/interception/ProcessorInterceptor.java
src/main/java/org/mule/runtime/api/interception/ProcessorParameterValue.java

MULE-13263: Interception API no calling before & around if the processor

---

src/main/java/org/mule/runtime/api/el/AbstractBindingContextBuilderFactory.java
src/main/java/org/mule/runtime/api/tls/AbstractTlsContextFactoryBuilderFactory.java

MULE-11767: Improve TLS API

---

src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java

MULE-13380: Provide a way to unregister ExceptionReader from

---

src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java
src/test/java/org/mule/runtime/api/exception/ExceptionHelperTestCase.java

* Avoid collisions between readers from different artifacts

MULE-13383: Fix ExceptionReader exceptionReaders list

---

src/main/java/org/mule/runtime/api/event/Event.java

* Change security filter return type to 
* Remove some deprecated usages
* Event interface split

MULE-13363: Allow access to session properties from privileged API

---

src/main/java/org/mule/runtime/api/component/location/ConfigurationComponentLocator.java

MULE-13506: ConfigurationComponentLocator.findAll does not return all

---

src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java

MULE-13764: When a MULE:UNKNOWN error is logged, always log the

---

src/main/java/org/mule/runtime/api/component/AbstractComponent.java
src/main/java/org/mule/runtime/api/event/EventContext.java

concurrency for GET operation
* microoptimizations in event creation

MULE-13779: CLONE - HTTP requester component degradation of 98% on high

---

src/main/java/org/mule/runtime/internal/util/StringByteSizeCalculator.java

MULE-13904: Time and resources wasted calculating String length in

---

pom.xml

_ Renaming api annotations artifact

MULE-14373 Define annotations to exclude java elements from the API

---

src/main/java/org/mule/runtime/api/meta/model/display/PathModel.java
src/main/java/org/mule/runtime/api/meta/model/error/ImmutableErrorModel.java
src/main/java/org/mule/runtime/api/meta/model/stereotype/ImmutableStereotypeModel.java
src/main/java/org/mule/runtime/api/metadata/DefaultMetadataKey.java

(cherry picked from commit 357f4fd)

MULE-14433: Replace usages of EqualsBuilder#reflectionEquals (#458)

---

src/main/java/org/mule/runtime/api/scheduler/SchedulerConfig.java

MULE-14510: Allows custom schedulers to use a `runInCaller` rejection

---

src/main/java/org/mule/runtime/api/el/BindingContextUtils.java

MULE-15325: BindingContext look up is showing significant performance

---

src/main/java/org/mule/runtime/api/scheduler/SchedulerService.java

MULE-15415: Scheduler Service: provide a method to determine if current

---

src/main/java/org/mule/runtime/api/el/DataTypeAware.java
src/main/java/org/mule/runtime/api/metadata/DataType.java
src/main/java/org/mule/runtime/api/util/MultiMap.java
src/test/java/org/mule/runtime/api/util/MultiMapTestCase.java

MULE-15668: Provide information about collection and Map items types to

---

src/main/java/org/mule/runtime/api/metadata/TypedValue.java

MULE-16320: Remove overhead in event/message creation handling in

---

src/main/java/org/mule/runtime/api/metadata/MediaType.java

MULE-16428: Performance improvements in `MediaType` for DataWeave

---

pom.xml

MULE-16765: Fix Mule 4 Status pipelines' failures

---

api-changes.json
src/main/java/org/mule/runtime/api/component/ComponentIdentifier.java
src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

MULE-16861: Normalize namespace usage in ComponentIdentifier between

---

src/main/java/org/mule/runtime/api/metadata/MediaType.java
src/main/java/org/mule/runtime/api/metadata/TypedValue.java

* Avoid allocations for MediaType without charset
* Implement toString in TypedValue to aid when debugging

MULE-16101: Miscellaneous performance improvements

---

src/main/java/org/mule/runtime/api/meta/model/ImportedTypeModel.java
src/main/java/org/mule/runtime/api/meta/model/SubTypesModel.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ExtensionDeclaration.java
src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ParameterDeclaration.java

MULE-17269: Validate stereotypes in topLevel allowed elements from

---

src/main/java/org/mule/runtime/api/component/AbstractComponent.java
src/main/java/org/mule/runtime/api/component/Component.java
src/main/java/org/mule/runtime/internal/dsl/DefaultDslResolvingContext.java
src/test/java/org/mule/runtime/api/meta/model/ArtifactDeclarationJsonSerializerTestCase.java

* futher ehnancement and fix tests

MULE-17203: Properly add doc: attributes as metadata

---

src/main/java/org/mule/runtime/api/util/MultiMap.java
src/test/java/org/mule/runtime/api/util/MultiMapTestCase.java

* Optimize cloning for immutability
* Add support for unmodifiable wrapping

MULE-17535: Performance improvements for MultiMap immutability

---

src/main/java/org/mule/runtime/api/functional/Either.java
src/test/java/org/mule/runtime/api/functional/EitherTestCase.java

* Fix for `reduce` with both values empty

MULE-17737: Move `Either` to `mule-api` (#609)

---

src/main/java/org/mule/runtime/api/functional/Either.java

* Add generic type to getValue()

MULE-17737: Move `Either` to `mule-api`

---

pom.xml
src/main/java/org/mule/runtime/api/meta/MuleVersion.java
src/test/java/org/mule/runtime/api/MuleVersionTestCase.java

Fix semver calculation in order to be compliant with 2.0 spec

MULE-17902: Version is not compliant with Semver 2.0

---

src/main/java/org/mule/runtime/api/functional/Either.java
src/test/java/org/mule/runtime/api/functional/EitherTestCase.java

MULE-17988: Do not use Optional in Either (#629)

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

MULE-16933: Increase coverage for processing strategy dispose in unit

---

src/main/java/org/mule/runtime/api/exception/MuleException.java

MULE-17924: Optimize error handling performance

---

src/main/java/org/mule/runtime/api/connection/RemoteConnectionException.java
src/main/java/org/mule/runtime/api/connection/SourceConnectionException.java
src/main/java/org/mule/runtime/api/connection/SourceRemoteConnectionException.java

MULE-18343: Source is not notified of failure on ConnectionException in

---

src/main/java/org/mule/runtime/api/component/location/ComponentLocation.java
src/main/java/org/mule/runtime/api/component/location/LocationPart.java
src/main/java/org/mule/runtime/api/util/ComponentLocationProvider.java

MULE-18354: Use OptionalInt rather than Optional<Integer> in

---

src/main/java/org/mule/runtime/api/el/BindingContextUtils.java
src/main/java/org/mule/runtime/api/message/Error.java

null
* Fix for errors in sdk operations

MULE-18535: #[message.message.exceptionPayload.info.Element] returns

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit ee5c535ac84b528645e03299001e5bdafdc46c0d)

MULE-18573: CursorProvider key collision at CursorProvider cache (#703)

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 11ab58ae7cc5607c278d746db445b09ec7c169eb)

MULE-18990: Add an optional warning with info about event dropped (#740)

---

api-changes.json
pom.xml
src/main/java/org/mule/runtime/api/util/IOUtils.java

(cherry picked from commit efe2960302fe5200f398c42defd0c85469227789)

MULE-14729: Support JDK9 (#481)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 7f8487ad6b222233f0b6982a3329c8aa129e1f89)

MULE-19038: feature flag reserved variable names (#748)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/Feature.java
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java

(cherry picked from commit 3d22024e16884ad365ed3fad92b29e6897575a3c)

MULE-18976: Implement Feature Flagging  (4.2.x) (#757)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit e4b07537690a472270af07e8fdbe389ddca710bb)

MULE-19218: Add feature flag to Remove intermediate commits from batch:aggregator (#791)

---

pom.xml

(cherry picked from commit 003d94c1eef7f41cad12b10d19bac09c1cdfcd65)

MULE-19224: Avoid forking the Java compiler (#797)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

MULE-19346: Revert sync/async operation execution resolution based on

---

api-changes.json
src/main/java/org/mule/runtime/api/component/ConfigurationProperties.java
src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

MULE-19406: Wrong property format "mule..enableStreamingStatistics"

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

* MULE-19586: feature flag MULE-19443
(cherry picked from commit 568662e9d93d726f315c56e92d2a0830ce53f448)

MULE-19586: feature flag MULE-19443 (#834)

---

api-changes.json
src/main/java/org/mule/runtime/api/meta/MuleVersion.java
src/test/java/org/mule/runtime/api/MuleVersionTestCase.java

(cherry picked from commit 12f69a370e1b8d29c3b068a1421c0d25357dc7e8)

MULE-19682: Feature flags evaluation must ignore semver suffixes

---

api-changes.json
src/main/java/org/mule/runtime/api/profiling/ProfilingDataConsumerDiscoveryStrategy.java

(cherry picked from commit b1ecdd18d99ebeff9c91f3d95442d70b7bc7346f)

MULE-19596: Implement a profiling data consumer discovery strategy based on server plugins

---

src/main/java/org/mule/runtime/api/deployment/meta/Product.java

MULE-19787: Account for the runtime extModel jars when looking for the

---

src/main/java/org/mule/runtime/api/exception/MuleException.java
src/test/java/org/mule/runtime/api/exception/MuleExceptionTestCase.java

(cherry picked from commit 3c0849d0fd0db13e8450e5548c23cd27f284ed75)

MULE-19811: The 'application/dw' transformation fails with NullPointerException i… (#889)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java

validation
* Fix enabled since version

MULE-19879: Add a feature flag to disable ErrorHandlerOnErrorTypeExists

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

* MULE-19942: move sysprop to mule-api
(cherry picked from commit f29984532716eebe2fe3b824240240454def35d5)

MULE-19942: move sysprop to mule-api (#927)

---

api-changes.json
src/main/java/org/mule/runtime/api/scheduler/SchedulerService.java

(cherry picked from commit 59f580ba0618dcda74df72c1fb61af1a518e1f22)

MULE-19537: App get stuck when is trying to read the error payload in the error handler after a failing http request (#941)

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 398eefb14e0afd3bcc3fa3deedfb79868e9b957c)

MULE-19984: Add system property for the new sorter

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit df4a3a724b8189da5aac55d90023df6422ccbaae)

W-10711033: adding system property to force Grizzly's `WorkerThreadIOStrategy` when TLS is enabled. (#957)

---

pom.xml

classpath causes compilation failure in integration-tests

W-11271603: com.vaadin.external.google:android-json dependency in

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

* W-11320853: add sysprop to disable jdk vendor validation
(cherry picked from commit 78a5c07e7607390d3a08af13aec2049fdf20f794)

W-11320853: add sysprop to disable jdk vendor validation (#1000)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

* W-11147961: Fixing Feature Flag javadoc
* Changing property name
(cherry picked from commit a8e342c4d24c1a0d46ae9b22cda944dea41afbdd)

W-11147961: Fixing Feature Flag name (#1006)

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

W-11643926: An error affecting the tracing should not affect the application execution

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 7f4e33abf3c47dd1c32296740d3ae15abc149eb7)

W-11308645: After calling an external SOAP endpoint, Error Objects are generated differently in MRT 4.3.0 and MRT 4.4.0

---

api-changes.json
src/main/java/org/mule/runtime/api/notification/PipelineMessageNotification.java

(cherry picked from commit c6fb104e3e3574b66464c2b68db4e171de688fec)

W-11861058: Allow obtaining the failing component from a PipelineMessageNotification (#1046)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

This reverts commit f01046283126e5a73d4a2117ce3c753aa39a689e.

W-12049036: Revert "W-10822938: Inconsistent behaviour when using insecure=true atribute of trust-store config (#1042) (#1039)"

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

This reverts commit 2d2eccc09af79f753e820536a180aea3cd9d580d.

W-12049036: Revert "W-10822938: Inconsistent behaviour when using insecure=true attribute of trust-store config (#1043) (#1039)"

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 16f7d57f59f513ea983f0ac6c9f4153f26ac8ff5)

W-12049036: Revert "W-10822938: Inconsistent behaviour when using insecure=true attribute of trust-store config (#1042) (#1039)" (#1055)

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

…g when deploying applications

W-12073186: Enable the possibility of parallel extension model loading when deploying applications

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 77666ba9226265068037af64d335e23319b23ece)

W-11529823: Idempotent Validation Filter does not cascade object store exception (#1064)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 011caaafc55da0ce9218e62776adc7e4c022a918)

W-12207110: Wrap an IllegalArgumentException in a MessagingException at ForeachRouter in order to fix an event stuck (#1078)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

This reverts the revert 086052816364d58f1f4b1868e8f0ffe504be2b3c.

W-10822938: Revert "Revert "Inconsistent behaviour when using insecure=true attribute of trust-store config (#1039)" (#1067)"

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 1056aaf042b541665510d3d29b4e54659416349c)

W-10822938: Revert "Revert "Inconsistent behaviour when using insecure=true attribute of trust-store config (#1039)" (#1067)" (#1070)

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

W-10825584: add overriding sysprop for DISABLE_REGISTRY_BOOTSTRAP_OPTIONAL_ENTRIES

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

W-10825584: add overriding sysprop for DISABLE_REGISTRY_BOOTSTRAP_OPTIONAL_ENTRIES (#1096)

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 9f788d527200f2fd934bcfe8fc0bf30d8a8dbd53)

W-12395077: adding support for `API` dependency types (#1102)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

---------
Co-authored-by: Fabian Gonzalez <fabian.gonzalez@mulesoft.com>
(cherry picked from commit f0c1b900f8d9bd792a3d6fe82370d04099a253bb)

W-12435158: Add a flag to enable/disable retrieval of config from app

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

Co-authored-by: Fabian Gonzalez <fabian.gonzalez@mulesoft.com>
(cherry picked from commit f0c1b900f8d9bd792a3d6fe82370d04099a253bb)

W-12435158: Add a flag to enable/disable retrieval of config from app (#1108)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit a50156a9b1ab7947d715a5dd85f82cbfab6de5f9)

W-11855052: Database Connector to connect to SQL Anywhere via the sajdbc4 driver

---

src/main/java/module-info.java
src/main/java/org/mule/runtime/internal/util/collection/UnmodifiableMap.java

W-12980686: Generate a module-info.java for mule-ee api modules

---

pom.xml

(cherry picked from commit 609afcd211f424f009ffd41061e66f677aa2a881)

W-13578394 - MULE-19224: Avoid forking the build to package sources (#809)

---

src/main/java/module-info.java

W-13659294: Modularize Mule integration tests runner

---

src/main/java/org/mule/runtime/internal/connectivity/ConnectivityTestingStrategyUtils.java

W-13691314: JPMS - ServiceLoader not loading same module services when

---

src/main/java/module-info.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

W-13748730: Add module-info to mule-core and services apis

---

pom.xml

* Addendum: replace javax.inject also

W-13588773: Replace all javax jars bundled in the runtime with the jakarta equivalent

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit be3e2bc06b323e55c2cc901f8bbd048fa9a4887a)

W-13588449: Parse template target value breaking change. (#1200)

---

src/main/java/module-info.java

W-13829740: Change classloader creation to use module layers

---

src/main/java/org/mule/runtime/api/deployment/meta/MuleApplicationModel.java
src/main/java/org/mule/runtime/api/deployment/meta/MuleDeployableModel.java
src/main/java/org/mule/runtime/api/deployment/meta/MuleDomainModel.java

which java version the app works for

W-14209023: Support in mule-artifact.json of a property that specifies

---

api-changes.json
src/main/java/org/mule/runtime/api/el/BindingContextUtils.java
src/main/java/org/mule/runtime/api/message/Error.java

* W-14067135: make Element DSL available in ExceptionPayload
* Address PR comments

W-14067135: make Element DSL available in ExceptionPayload (#1229)

---

src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java

(cherry picked from commit cd929c3c88f3b2943ebe69677a9b7c65d3f4bbee)

W-14488411: Provide an API for building/querying the registry (#1251)

---

src/main/java/org/mule/runtime/api/metadata/MediaType.java
src/test/java/org/mule/runtime/api/test/metadata/MediaTypeTestCase.java

…OM issue (#1259)
* add test
* W-14490182: Set maximum cache size for MediaType to prevent attacks/OOM issue

W-14490182: Set maximum cache size for MediaType

---

src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/NestedRouteDeclarer.java

W-14781155: Inconsistent error-handler definition as part of the core

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

…tions and rollbacks are being silently executed (#1278)"
This reverts commit b1b397ef272ae7c6897a509fb8f169357b6b319a.

W-14608096: reverting changes

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

This reverts commit 77547fb9a060884b4cf002877a44fe0af377968c.

W-15008528: Complete fix for W-14608096 and feature flags

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

W-14572236: Remove killswitches

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 2cfe77e4b83d0bf4576bda7d14d243c1f2c1902d)

W-15141905: Adding flag for TP compatibility mode. (#1321)

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 2cfe77e4b83d0bf4576bda7d14d243c1f2c1902d) (cherry picked from commit 3aea4dcaea150a3a5ad25c5cd97f4f35b633cfa1)

W-15141905: Adding flag for TP compatibility mode. (#1321) (#1328)

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 2cfe77e4b83d0bf4576bda7d14d243c1f2c1902d)
(cherry picked from commit e11e3332851ff2a18ff2f44c7704c75d496319e5)

W-15141905: Adding flag for TP compatibility mode. (#1321) (#1327)

---

src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 1415263b38f1f3f36b8c40c114cefc281372bae2)

W-15206528: Clear MDC context (#1347)

---

src/main/java/module-info.java
src/main/java/org/mule/runtime/api/exception/ExceptionHelper.java
src/main/java/org/mule/runtime/internal/exception/SuppressedMuleException.java
src/main/java/org/mule/runtime/privileged/exception/SuppressedMuleException.java
src/test/java/org/mule/runtime/api/test/internal/exception/SuppressedMuleExceptionTestCase.java

…ge in order to make it exportable).

W-15643200: output json --- error fails with NullPointerException after "MULE:RETRIES_EXHAUSTED"

---

api-changes.json
src/main/java/org/mule/runtime/api/component/TypedComponentIdentifier.java

(cherry picked from commit f2fbf2198ee3a5d27cd8609c8f2ca8f81b777c86)

W-16230302: Adding TypedComponentIdentifier for Subflows (#1387)

---

src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
src/test/java/module-info.java
src/test/java/org/mule/runtime/api/test/component/DefaultComponentIdentifierTestCase.java

(W-16237424 https://github.com/mulesoft/mule-api/pull/1408)

W-16562720 [Cherry pick] Add trim to() DefaultComponentIdentifier builder

---

src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
src/test/java/module-info.java
src/test/java/org/mule/runtime/api/test/component/DefaultComponentIdentifierTestCase.java

(W-16237424 https://github.com/mulesoft/mule-api/pull/1408)

W-16562717 [Cherry pick] Add trim to() DefaultComponentIdentifier builder

---

src/main/java/org/mule/runtime/api/artifact/ArtifactType.java

(cherry picked from commit db086763224eb8380e107fb554310c3fde441eeb)

W-16447481: Move ArtifactType to mule-api (#1382)

---

pom.xml

W-16644064 update old artifacts for 1.6.x

W-16644064 update old artifacts for 1.6.x

---

src/main/java/org/mule/runtime/api/component/DefaultComponentIdentifier.java
src/test/java/module-info.java
src/test/java/org/mule/runtime/api/test/component/DefaultComponentIdentifierTestCase.java

(W-16237424 https://github.com/mulesoft/mule-api/pull/1408)

W-16562713 [Cherry pick] Add trim to() DefaultComponentIdentifier builder

---

src/main/java/module-info.java
src/main/java/org/mule/runtime/api/metadata/DataType.java
src/main/java/org/mule/runtime/api/notification/AbstractServerNotification.java

(cherry picked from commit d7e6c15e4a77a63e2a703f934b60e7689917f08b)

W-16584126: PolyMule fixes (#1431)

---

pom.xml
src/main/java/org/mule/runtime/api/deployment/meta/MulePluginModel.java

* Add constant
* piggy-back: pom cleanup

W-15934585: Validate that the lower supported java version of the extension matches the byte code level

---

src/main/java/org/mule/runtime/internal/util/classloader/CallerClassUtils.java

* Improvement in `CallerClassUtils`

W-16676308: Microbenchmarks for big ASTs

---

src/main/java/org/mule/runtime/api/metadata/AbstractDataTypeBuilderFactory.java
src/main/java/org/mule/runtime/api/metadata/DataType.java

* AbstractDataTypeBuilderFactory cache
* Optimize DynamicDelegateDataType hashCode

W-16789915: [Embedded Framework] Review performance

---

src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit a822c3119863d3a38eb88511b418f368a9a04743)

W-17403761: Redelivery Policy - infinite loop when the redelivery is exhausted in a source configured with transactions and On Error Propagate (#1488)

---

api-changes.json
src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
src/main/java/org/mule/runtime/api/meta/MuleVersion.java
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit f085f4072cbee15e23efd6221665a023a98559e1)

W-16941297: Adding feature flag for ForkJoinRouters to complete their child contexts on timeout.

---

src/main/java/module-info.java
src/main/java/org/mule/runtime/api/component/AbstractComponent.java
src/main/java/org/mule/runtime/api/component/Component.java
src/main/java/org/mule/runtime/api/component/location/Location.java
src/main/java/org/mule/runtime/api/event/EventContext.java
src/test/java/org/mule/runtime/api/test/component/ComponentRepresentationTestCase.java

* add getStartTime to EventContext

W-18267133: Improvements for FlowStack

---

api-changes.json
src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java

(cherry picked from commit 540d1d5d5318f2f889f6e9d1e6c6dea64c0a5eba)

W-18324755: Re introduce W-13588449 fix. (#1557)

---

src/main/java/org/mule/runtime/api/connectivity/ConnectivityTestingService.java
src/main/java/org/mule/runtime/api/connectivity/ConnectivityTestingStrategy.java
src/main/java/org/mule/runtime/api/tx/DataSourceDecorator.java

* piggyback: deprecate MTS specific api

W-18326147: Deprecate current APIs specific for btm
